from __future__ import annotations

import json
import re
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import netCDF4
import numpy as np
import polars as pl
import pyarrow as pa

from adqat import __version__
from adqat.config import ResolvedConfig
from adqat.periods import Period

CROCUS_LEVEL_STATEMENT = (
    "CROCUS ARM-inspired naming and processing levels; "
    "not an ARM datastream level designation."
)
FLAG_NAME = re.compile(r"^[A-Za-z0-9_]+$")


class NetCDFError(RuntimeError):
    """Raised when a native Level 1 NetCDF artifact cannot be created or verified."""


def native_a1_filename(config: ResolvedConfig, period: Period) -> str:
    netcdf = config.run.output.netcdf
    if netcdf is None:
        raise NetCDFError("NetCDF output is not configured")
    _validate_daily_period(period)
    vsn = str(config.work_unit.filters["vsn"])
    start = period.start.strftime("%Y%m%dT%H%M%SZ")
    end = period.end.strftime("%Y%m%dT%H%M%SZ")
    return f"{netcdf.site}.{netcdf.instrument}.{vsn}.native.a1.{start}-{end}.nc"


def write_native_a1(
    data: pl.DataFrame,
    qc_flags_path: Path,
    destination: Path,
    period: Period,
    config: ResolvedConfig,
    run_id: str,
    input_fingerprint: str,
    source_file_count: int,
) -> Path:
    """Write and reopen a deterministic, long-form native Level 1 file."""
    expected_name = native_a1_filename(config, period)
    if destination.name != expected_name:
        raise NetCDFError(f"NetCDF destination must be named {expected_name!r}")
    frame = _attach_flags(data, qc_flags_path, config)
    time_name = config.run.source.time.column
    time_ns = frame.get_column(time_name).to_physical().to_numpy().astype(np.int64, copy=False)
    coverage = _coverage_attributes(time_ns, period)

    try:
        with netCDF4.Dataset(destination, "w", format="NETCDF4") as dataset:
            dataset.createDimension("observation", frame.height)
            _write_global_attributes(
                dataset,
                config,
                period,
                run_id,
                input_fingerprint,
                source_file_count,
                coverage,
            )
            _write_observation_variables(dataset, frame, time_name, config)
    except Exception as error:
        destination.unlink(missing_ok=True)
        raise NetCDFError(f"failed to write {destination.name}: {error}") from error

    _verify_native_a1(destination, frame.height, period, config)
    return destination


def _attach_flags(
    data: pl.DataFrame,
    qc_flags_path: Path,
    config: ResolvedConfig,
) -> pl.DataFrame:
    join_keys = [*config.run.source.observation_keys, "variable"]
    flags = pl.read_parquet(qc_flags_path).select(*join_keys, "qc_bits")
    frame = (
        data.drop("_source_file")
        .join(flags, on=join_keys, how="left")
        .with_columns(pl.col("qc_bits").fill_null(0).cast(pl.UInt64))
    )
    return frame


def _write_global_attributes(
    dataset: Any,
    config: ResolvedConfig,
    period: Period,
    run_id: str,
    input_fingerprint: str,
    source_file_count: int,
    coverage: dict[str, str],
) -> None:
    netcdf = config.run.output.netcdf
    if netcdf is None:  # pragma: no cover - guarded by native_a1_filename
        raise NetCDFError("NetCDF output is not configured")
    created = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    attributes = {
        "title": f"CROCUS {netcdf.instrument.upper()} native Level 1 observations",
        "summary": "Native-timestamp observations with ADQAT QC bit masks.",
        "Conventions": "CF-1.10, ACDD-1.3",
        "crocus_level_statement": CROCUS_LEVEL_STATEMENT,
        "crocus_filename_convention": (
            "{site}.{instrument}.{vsn}.{integration}.{level}."
            "{start_utc}-{end_utc}.nc"
        ),
        "crocus_processing_level": "1",
        "crocus_data_level": "a1",
        "crocus_medallion": "silver",
        "source_dataset_fingerprint": input_fingerprint,
        "source_snapshot": config.source_path,
        "source_file_count": np.int64(source_file_count),
        "qaqc_rule_fingerprint": config.config_hash,
        "aggregation_rule_fingerprint": "not_applicable",
        "processing_software_version": __version__,
        "site_id": netcdf.site,
        "vsn": str(config.work_unit.filters["vsn"]),
        "instrument_id": str(config.work_unit.filters["instrument_id"]),
        "instrument_model": str(config.work_unit.filters["sensor"]),
        "run_id": run_id,
        "work_unit_id": config.work_unit.id,
        "nominal_period_start": _format_datetime(period.start),
        "nominal_period_end": _format_datetime(period.end),
        "date_created": created,
        "history": f"{created} generated by ADQAT {__version__}",
        **coverage,
    }
    dataset.setncatts(attributes)


def _write_observation_variables(
    dataset: Any,
    frame: pl.DataFrame,
    time_name: str,
    config: ResolvedConfig,
) -> None:
    time_ns = frame.get_column(time_name).to_physical().to_numpy().astype(np.int64, copy=False)
    time = dataset.createVariable(time_name, "i8", ("observation",), zlib=True, complevel=4)
    time.long_name = "observation time"
    time.standard_name = "time"
    time.units = "nanoseconds since 1970-01-01 00:00:00 UTC"
    time.calendar = "proleptic_gregorian"
    time[:] = time_ns

    for key in config.run.source.observation_keys:
        if key == time_name:
            continue
        _write_observation_key(dataset, frame, key)

    variable_names = list(config.profile.variables)
    variable_codes = {name: index for index, name in enumerate(variable_names)}
    profile_variable = dataset.createVariable(
        "variable", "u2", ("observation",), zlib=True, complevel=4
    )
    profile_variable.long_name = "ADQAT profile variable code"
    profile_variable.code_table = json.dumps(
        {
            str(code): {
                "name": name,
                "measurement": str(config.profile.variables[name].where["measurement"]),
                "field": str(config.profile.variables[name].where["field"]),
                "units": config.profile.variables[name].units or "1",
                "data_type": config.profile.variables[name].data_type,
            }
            for name, code in variable_codes.items()
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    profile_variable.flag_values = np.arange(len(variable_names), dtype=np.uint16)
    profile_variable.flag_meanings = " ".join(variable_names)
    profile_variable[:] = (
        frame.get_column("variable")
        .replace_strict(variable_codes, return_dtype=pl.UInt16)
        .to_numpy()
        .astype(np.uint16, copy=False)
    )

    observed = dataset.createVariable(
        "observed_value",
        "f8",
        ("observation",),
        fill_value=np.nan,
        zlib=True,
        complevel=4,
    )
    observed.long_name = "quality-controlled numeric observation"
    observed.coordinates = time_name
    observed_values = (
        frame.get_column("observed_value")
        .fill_null(float("nan"))
        .to_numpy()
        .astype(np.float64, copy=False)
    )
    observed[:] = observed_values

    observed_strings = frame.get_column("observed_value_string")
    if observed_strings.null_count() < frame.height:
        observed_string = dataset.createVariable("observed_value_string", str, ("observation",))
        observed_string.long_name = "quality-controlled string observation"
        observed_string.coordinates = time_name
        observed_string.missing_value = ""
        observed_string[:] = np.asarray(
            ["" if value is None else value for value in observed_strings], dtype=object
        )

    qc = dataset.createVariable("qc_bits", "u8", ("observation",), zlib=True, complevel=4)
    qc.long_name = "ADQAT quality-control bit mask; zero means no configured check failed"
    qc.coordinates = time_name
    flag_items = sorted(config.rules.flags.items(), key=lambda item: item[1].bit)
    if any(not FLAG_NAME.fullmatch(name) for name, _ in flag_items):
        raise NetCDFError(
            "flag names must contain only letters, digits, and underscores for NetCDF"
        )
    qc.flag_masks = np.asarray(
        [1 << definition.bit for _, definition in flag_items], dtype=np.uint64
    )
    qc.flag_meanings = " ".join(name for name, _ in flag_items)
    qc[:] = frame.get_column("qc_bits").to_numpy().astype(np.uint64, copy=False)


def _coverage_attributes(
    time_ns: np.ndarray[Any, np.dtype[np.int64]], period: Period
) -> dict[str, str]:
    if time_ns.size == 0:
        return {
            "time_coverage_start": _format_datetime(period.start),
            "time_coverage_end": _format_datetime(period.start),
            "time_coverage_duration": "PT0S",
            "time_coverage_resolution": "not_applicable",
        }
    first_second = int(time_ns.min()) // 1_000_000_000
    last_second_exclusive = int(time_ns.max()) // 1_000_000_000 + 1
    return {
        "time_coverage_start": _format_epoch_second(first_second),
        "time_coverage_end": _format_epoch_second(last_second_exclusive),
        "time_coverage_duration": _iso_duration_ns(
            (last_second_exclusive - first_second) * 1_000_000_000
        ),
        "time_coverage_resolution": "variable-dependent native sampling",
    }


def _verify_native_a1(
    path: Path,
    expected_rows: int,
    period: Period,
    config: ResolvedConfig,
) -> None:
    netcdf = config.run.output.netcdf
    if netcdf is None:  # pragma: no cover - writer cannot be called without this configuration
        raise NetCDFError("NetCDF output is not configured")
    try:
        with netCDF4.Dataset(path, "r") as dataset:
            if len(dataset.dimensions["observation"]) != expected_rows:
                raise NetCDFError("NetCDF observation count does not match selected source rows")
            for attribute in (
                "source_dataset_fingerprint",
                "qaqc_rule_fingerprint",
                "time_coverage_start",
                "time_coverage_end",
            ):
                if attribute not in dataset.ncattrs():
                    raise NetCDFError(f"NetCDF is missing required attribute {attribute!r}")
            if dataset.getncattr("site_id") != netcdf.site:
                raise NetCDFError("NetCDF site does not match configuration")
            if expected_rows:
                values = np.asarray(dataset.variables[config.run.source.time.column][:])
                lower = int(period.start.timestamp()) * 1_000_000_000
                upper = int(period.end.timestamp()) * 1_000_000_000
                if int(values.min()) < lower or int(values.max()) >= upper:
                    raise NetCDFError("NetCDF contains observations outside its nominal bounds")
    except NetCDFError:
        raise
    except Exception as error:
        raise NetCDFError(f"failed to verify {path.name}: {error}") from error


def _validate_daily_period(period: Period) -> None:
    if period.end - period.start != timedelta(days=1):
        raise NetCDFError("native NetCDF output requires an exact one-day period")
    for boundary in (period.start, period.end):
        if boundary.tzinfo is None or boundary.utcoffset() != timedelta(0):
            raise NetCDFError("native NetCDF period bounds must be UTC")
        if (boundary.hour, boundary.minute, boundary.second, boundary.microsecond) != (0, 0, 0, 0):
            raise NetCDFError("native NetCDF period bounds must be UTC midnights")


def _write_observation_key(dataset: Any, frame: pl.DataFrame, key: str) -> None:
    series = frame.get_column(key)
    if series.dtype == pl.Binary:
        values = _fixed_binary_matrix(series, width=16)
        dimension = f"{key}_byte"
        dataset.createDimension(dimension, values.shape[1])
        variable = dataset.createVariable(
            key, "u1", ("observation", dimension), zlib=True, complevel=4
        )
        variable.long_name = f"source observation key: {key}"
        variable.encoding = "16-byte binary identifier"
        variable[:] = values
        return
    encoded = np.asarray([str(value) for value in series], dtype=object)
    variable = dataset.createVariable(key, str, ("observation",))
    variable.long_name = f"source observation key: {key}"
    if encoded.size:
        variable[:] = encoded


def _fixed_binary_matrix(series: pl.Series, width: int) -> np.ndarray[Any, np.dtype[np.uint8]]:
    arrow = series.to_arrow()
    if isinstance(arrow, pa.ChunkedArray):
        arrow = arrow.combine_chunks()
    if arrow.null_count:
        raise NetCDFError(f"binary observation key {series.name!r} contains nulls")
    if pa.types.is_fixed_size_binary(arrow.type):
        if arrow.type.byte_width != width:
            raise NetCDFError(f"binary observation key {series.name!r} is not {width} bytes")
        buffer = arrow.buffers()[1]
        if buffer is None:
            return np.empty((0, width), dtype=np.uint8)
        offset = arrow.offset * width
    elif pa.types.is_binary(arrow.type) or pa.types.is_large_binary(arrow.type):
        offset_type = np.int64 if pa.types.is_large_binary(arrow.type) else np.int32
        offsets_buffer = arrow.buffers()[1]
        buffer = arrow.buffers()[2]
        if offsets_buffer is None or buffer is None:
            return np.empty((0, width), dtype=np.uint8)
        offsets = np.frombuffer(
            offsets_buffer,
            dtype=offset_type,
            count=len(arrow) + 1,
            offset=arrow.offset * np.dtype(offset_type).itemsize,
        )
        if np.any(np.diff(offsets) != width):
            raise NetCDFError(f"binary observation key {series.name!r} is not {width} bytes")
        offset = int(offsets[0])
    else:  # pragma: no cover - Polars Binary maps to an Arrow binary representation
        raise NetCDFError(f"unsupported binary Arrow type {arrow.type}")
    return np.frombuffer(buffer, dtype=np.uint8, count=len(arrow) * width, offset=offset).reshape(
        len(arrow), width
    )


def _format_datetime(value: datetime) -> str:
    return value.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _format_epoch_second(value: int) -> str:
    return _format_datetime(datetime(1970, 1, 1, tzinfo=UTC) + timedelta(seconds=value))


def _iso_duration_ns(value: int) -> str:
    seconds, nanoseconds = divmod(value, 1_000_000_000)
    if nanoseconds == 0:
        return f"PT{seconds}S"
    fraction = f"{nanoseconds:09d}".rstrip("0")
    return f"PT{seconds}.{fraction}S"
